sonar.projectKey=MathGo-Frontend
sonar.projectName=MathGo-Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/environments/**,**/*.html,**/*.scss,**/*.css
sonar.javascript.lcov.reportPaths=coverage/mathgo-frontend/lcov.info
sonar.typescript.lcov.reportPaths=coverage/mathgo-frontend/lcov.info
sonar.host.url=http://localhost:9000
sonar.token=sqp_f338ed69d4cff43e424f5ce603ea5905d1b68adc